name: Deplot Python Playground
on:
  push:
    branches:
      - website
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check website files
        run: |
          test -f docs/index.html
          test -f docs/style.css
      
      - name: validate html
        run: |
          npm install -g html-validate
          html-validate docs/index.html

      - name: check links
        uses: lycheever/lychee-action@v2
        with:
          args: --verbose --no-progress docs/**/*.html

      - name: validate css
        run: |
          npm install -g stylelint
          stylelint docs/style.css

      